---
title: "ABOUT"
date: '2022-06-24'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## BACKGROUND
I am a former researcher in psycho-oncology and currently work in the domain of
cardiological epidemiology. Here I use a mixture of classical statistical
and modern machine learning methods to build prediction models for the onset of
cardiovascular disease.

## PUBLICATIONS
### RESEARCH
As a researcher I have authored and co-authored several research papers and
posters, most of which can be found
[**here**](https://scholar.google.com/citations?user=fzccSmMAAAAJ/).

### R PACKAGES
I am also a developer of R packages
[**prepareD**](https://github.com/janbrederecke/prepareD/),
[**analyzeD**](https://github.com/janbrederecke/analyzeD/),
[**visualizeD**](https://github.com/janbrederecke/visualizeD/),
and [**predicteD**](https://github.com/janbrederecke/predicteD/)
that are designed to improve data analysis workflows in my
current projects. In addition, I am a contributor to the [**climbeR**](https://github.com/johnkarlen/climbeR/) package
that can be used to visualize results of random forest models and will soon be
available again on CRAN.

## LATELY
### R SHINY
I currently work on the development of multiple Shiny apps e.g. for the
European Heart Failure Score project and others.